const tslintSonarRulesConfig = {
    'no-all-duplicated-branches': true,
    'no-case-with-or': true,
    'no-collection-size-mischeck': true,
    'no-element-overwrite': true,
    'no-empty-destructuring': true,
    'no-identical-conditions': true,
    'no-identical-expressions': true,
    'no-ignored-initial-value': true,
    'no-ignored-return': true,
    'no-in-misuse': true,
    'no-misleading-array-reverse': true,
    'no-misspelled-operator': true,
    'no-self-assignment': true,
    'no-unthrown-error': true,
    'no-use-of-empty-return-value': true,
    'no-useless-increment': true,
    'no-useless-intersection': true,
    'cognitive-complexity': true,
    'consecutive-overloads': true,
    'max-union-size': true,
    'mccabe-complexity': false, // Other rules mesure this
    'no-accessor-field-mismatch': true,
    'no-array-delete': true,
    'no-big-function': true,
    'no-collapsible-if': true,
    'no-commented-code': true,
    'no-dead-store': true,
    'no-duplicate-in-composite': true,
    'no-duplicate-string': true,
    'no-duplicated-branches': true,
    'no-empty-nested-blocks': true,
    'no-extra-semicolon': true,
    'no-gratuitous-expressions': true,
    'no-hardcoded-credentials': true,
    'no-identical-functions': true,
    'no-inconsistent-return': true,
    'no-invalid-await': true,
    'no-invariant-return': true,
    'no-inverted-boolean-check': true,
    'no-multiline-string-literals': true,
    'no-nested-incdec': true,
    'no-nested-template-literals': true,
    'no-redundant-boolean': true,
    'no-redundant-jump': true,
    'no-redundant-parentheses': true,
    'no-return-type-any': true,
    'no-same-line-conditional': true,
    'no-small-switch': true,
    'no-statements-same-line': true,
    'no-unconditional-jump': true,
    'no-undefined-argument': true,
    'no-unenclosed-multiline-block': true,
    'no-unused-array': true,
    'no-useless-cast': true,
    'no-variable-usage-before-declaration': true,
    'parameters-max-number': true,
    'prefer-default-last': true,
    'prefer-immediate-return': false, // Sometimes naming the return value can be more readable.
    'prefer-optional': true,
    'prefer-promise-shorthand': true,
    'use-primitive-type': true,
    'use-type-alias': true,
};

module.exports = {
    tslintSonarRulesConfig,
};
